/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bo.edu.uagrm.ficct.inf310sb.proyecto1.Presentacion;


import bo.edu.uagrm.ficct.inf310sb.proyecto1.ArbolBinario;
import bo.edu.uagrm.ficct.inf310sb.proyecto1.PostFija;
import java.util.Queue;
import javax.swing.JOptionPane;

/**
 *
 * @author
 */
public class FProyecto extends javax.swing.JFrame {
String S="";
    ArbolBinario<String> arbolPrueba = new ArbolBinario<>();
PostFija r=new PostFija();

    /**
     * Creates new form FProyecto
     */
    public FProyecto() {
        initComponents();
        setLocationRelativeTo(null);
    }
   
    private boolean comprobarp(){//Verifica si los parentesis estan balanc
       String e=PANTALLA.getText();
        int i=0;
        int ayuda=0;
        while(i<e.length()){
            if(e.charAt(i)=='('){
                ayuda++;
            }else if(e.charAt(i)==')'){
                ayuda--;
            }
           if(ayuda<0){
               return false;
           }
           i++;
        }
        return (ayuda==0);
    }
    
    private boolean comp(){
        String e=PANTALLA.getText();
        int n=0;
        int A=0;
        while(n<e.length()&&A<2){
            if(!arbolPrueba.isOperator(String.valueOf(e.charAt(n)))){
                A=0; 
            }
            if (arbolPrueba.isOperator(String.valueOf(e.charAt(n)))) {
                A++;
            }
            n++;
        }
        return(A==0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        MULT = new javax.swing.JButton();
        REST = new javax.swing.JButton();
        DIV = new javax.swing.JButton();
        RESULTADO = new javax.swing.JButton();
        SUMA = new javax.swing.JButton();
        POTENCIA = new javax.swing.JButton();
        CE = new javax.swing.JButton();
        RES = new javax.swing.JButton();
        PB = new javax.swing.JButton();
        TRES = new javax.swing.JButton();
        CERO = new javax.swing.JButton();
        PA = new javax.swing.JButton();
        SIETE = new javax.swing.JButton();
        NUEVE = new javax.swing.JButton();
        SEIS = new javax.swing.JButton();
        CUATRO = new javax.swing.JButton();
        DOS = new javax.swing.JButton();
        UNO = new javax.swing.JButton();
        OCHO = new javax.swing.JButton();
        CINCO = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        PANTALLA = new javax.swing.JLabel();
        INFIJA = new javax.swing.JLabel();
        RESULTADOP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(24, 27, 32));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MULT.setBackground(new java.awt.Color(51, 51, 51));
        MULT.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        MULT.setForeground(new java.awt.Color(0, 0, 0));
        MULT.setText("x");
        MULT.setBorderPainted(false);
        MULT.setDefaultCapable(false);
        MULT.setFocusPainted(false);
        MULT.setFocusable(false);
        MULT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MULT.setMaximumSize(new java.awt.Dimension(40, 40));
        MULT.setMinimumSize(new java.awt.Dimension(40, 40));
        MULT.setPreferredSize(new java.awt.Dimension(50, 50));
        MULT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MULTActionPerformed(evt);
            }
        });
        jPanel2.add(MULT, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        REST.setBackground(new java.awt.Color(51, 51, 51));
        REST.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        REST.setForeground(new java.awt.Color(0, 0, 0));
        REST.setText("-");
        REST.setBorderPainted(false);
        REST.setDefaultCapable(false);
        REST.setFocusPainted(false);
        REST.setFocusable(false);
        REST.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        REST.setMaximumSize(new java.awt.Dimension(40, 40));
        REST.setMinimumSize(new java.awt.Dimension(40, 40));
        REST.setPreferredSize(new java.awt.Dimension(50, 50));
        REST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESTActionPerformed(evt);
            }
        });
        jPanel2.add(REST, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        DIV.setBackground(new java.awt.Color(51, 51, 51));
        DIV.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        DIV.setForeground(new java.awt.Color(0, 0, 0));
        DIV.setText("/");
        DIV.setBorderPainted(false);
        DIV.setDefaultCapable(false);
        DIV.setFocusPainted(false);
        DIV.setFocusable(false);
        DIV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DIV.setMaximumSize(new java.awt.Dimension(40, 40));
        DIV.setMinimumSize(new java.awt.Dimension(40, 40));
        DIV.setPreferredSize(new java.awt.Dimension(50, 50));
        DIV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DIVActionPerformed(evt);
            }
        });
        jPanel2.add(DIV, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        RESULTADO.setBackground(new java.awt.Color(51, 51, 51));
        RESULTADO.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        RESULTADO.setForeground(new java.awt.Color(0, 0, 0));
        RESULTADO.setText("=");
        RESULTADO.setBorderPainted(false);
        RESULTADO.setDefaultCapable(false);
        RESULTADO.setFocusPainted(false);
        RESULTADO.setFocusable(false);
        RESULTADO.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RESULTADO.setMaximumSize(new java.awt.Dimension(40, 40));
        RESULTADO.setMinimumSize(new java.awt.Dimension(40, 40));
        RESULTADO.setPreferredSize(new java.awt.Dimension(50, 50));
        RESULTADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESULTADOActionPerformed(evt);
            }
        });
        jPanel2.add(RESULTADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        SUMA.setBackground(new java.awt.Color(51, 51, 51));
        SUMA.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        SUMA.setForeground(new java.awt.Color(0, 0, 0));
        SUMA.setText("+");
        SUMA.setBorderPainted(false);
        SUMA.setDefaultCapable(false);
        SUMA.setFocusPainted(false);
        SUMA.setFocusable(false);
        SUMA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SUMA.setMaximumSize(new java.awt.Dimension(40, 40));
        SUMA.setMinimumSize(new java.awt.Dimension(40, 40));
        SUMA.setPreferredSize(new java.awt.Dimension(50, 50));
        SUMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUMAActionPerformed(evt);
            }
        });
        jPanel2.add(SUMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, 50));

        POTENCIA.setBackground(new java.awt.Color(51, 51, 51));
        POTENCIA.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        POTENCIA.setForeground(new java.awt.Color(0, 0, 0));
        POTENCIA.setText("^");
        POTENCIA.setBorderPainted(false);
        POTENCIA.setDefaultCapable(false);
        POTENCIA.setFocusPainted(false);
        POTENCIA.setFocusable(false);
        POTENCIA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        POTENCIA.setMaximumSize(new java.awt.Dimension(40, 50));
        POTENCIA.setMinimumSize(new java.awt.Dimension(40, 50));
        POTENCIA.setPreferredSize(new java.awt.Dimension(50, 50));
        POTENCIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                POTENCIAActionPerformed(evt);
            }
        });
        jPanel2.add(POTENCIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        CE.setBackground(new java.awt.Color(51, 51, 51));
        CE.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CE.setForeground(new java.awt.Color(0, 0, 0));
        CE.setText("C");
        CE.setBorderPainted(false);
        CE.setDefaultCapable(false);
        CE.setFocusPainted(false);
        CE.setFocusable(false);
        CE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CE.setMaximumSize(new java.awt.Dimension(40, 50));
        CE.setMinimumSize(new java.awt.Dimension(40, 50));
        CE.setPreferredSize(new java.awt.Dimension(50, 50));
        CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CEActionPerformed(evt);
            }
        });
        jPanel2.add(CE, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, 50));

        RES.setBackground(new java.awt.Color(51, 51, 51));
        RES.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        RES.setForeground(new java.awt.Color(0, 0, 0));
        RES.setText("<");
        RES.setBorderPainted(false);
        RES.setDefaultCapable(false);
        RES.setFocusPainted(false);
        RES.setFocusable(false);
        RES.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RES.setMaximumSize(new java.awt.Dimension(40, 50));
        RES.setMinimumSize(new java.awt.Dimension(40, 50));
        RES.setPreferredSize(new java.awt.Dimension(50, 50));
        RES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESActionPerformed(evt);
            }
        });
        jPanel2.add(RES, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, 50));

        PB.setBackground(new java.awt.Color(51, 51, 51));
        PB.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PB.setForeground(new java.awt.Color(235, 236, 240));
        PB.setText(")");
        PB.setBorderPainted(false);
        PB.setDefaultCapable(false);
        PB.setFocusPainted(false);
        PB.setFocusable(false);
        PB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PB.setMaximumSize(new java.awt.Dimension(40, 40));
        PB.setMinimumSize(new java.awt.Dimension(40, 40));
        PB.setPreferredSize(new java.awt.Dimension(50, 50));
        PB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PBActionPerformed(evt);
            }
        });
        jPanel2.add(PB, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        TRES.setBackground(new java.awt.Color(51, 51, 51));
        TRES.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        TRES.setForeground(new java.awt.Color(235, 236, 240));
        TRES.setText("3");
        TRES.setBorderPainted(false);
        TRES.setDefaultCapable(false);
        TRES.setFocusPainted(false);
        TRES.setFocusable(false);
        TRES.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TRES.setPreferredSize(new java.awt.Dimension(50, 50));
        TRES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TRESActionPerformed(evt);
            }
        });
        jPanel2.add(TRES, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        CERO.setBackground(new java.awt.Color(51, 51, 51));
        CERO.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CERO.setForeground(new java.awt.Color(235, 236, 240));
        CERO.setText("0");
        CERO.setBorderPainted(false);
        CERO.setDefaultCapable(false);
        CERO.setFocusPainted(false);
        CERO.setFocusable(false);
        CERO.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CERO.setPreferredSize(new java.awt.Dimension(50, 50));
        CERO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CEROActionPerformed(evt);
            }
        });
        jPanel2.add(CERO, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        PA.setBackground(new java.awt.Color(51, 51, 51));
        PA.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PA.setForeground(new java.awt.Color(235, 236, 240));
        PA.setText("(");
        PA.setBorderPainted(false);
        PA.setDefaultCapable(false);
        PA.setFocusPainted(false);
        PA.setFocusable(false);
        PA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PA.setMaximumSize(new java.awt.Dimension(40, 40));
        PA.setMinimumSize(new java.awt.Dimension(40, 40));
        PA.setPreferredSize(new java.awt.Dimension(50, 50));
        PA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PAActionPerformed(evt);
            }
        });
        jPanel2.add(PA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        SIETE.setBackground(new java.awt.Color(51, 51, 51));
        SIETE.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        SIETE.setForeground(new java.awt.Color(235, 236, 240));
        SIETE.setText("7");
        SIETE.setBorderPainted(false);
        SIETE.setDefaultCapable(false);
        SIETE.setFocusPainted(false);
        SIETE.setFocusable(false);
        SIETE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SIETE.setPreferredSize(new java.awt.Dimension(50, 50));
        SIETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIETEActionPerformed(evt);
            }
        });
        jPanel2.add(SIETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        NUEVE.setBackground(new java.awt.Color(51, 51, 51));
        NUEVE.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        NUEVE.setForeground(new java.awt.Color(235, 236, 240));
        NUEVE.setText("9");
        NUEVE.setBorderPainted(false);
        NUEVE.setDefaultCapable(false);
        NUEVE.setFocusPainted(false);
        NUEVE.setFocusable(false);
        NUEVE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        NUEVE.setPreferredSize(new java.awt.Dimension(50, 50));
        NUEVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUEVEActionPerformed(evt);
            }
        });
        jPanel2.add(NUEVE, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        SEIS.setBackground(new java.awt.Color(51, 51, 51));
        SEIS.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        SEIS.setForeground(new java.awt.Color(235, 236, 240));
        SEIS.setText("6");
        SEIS.setBorderPainted(false);
        SEIS.setDefaultCapable(false);
        SEIS.setFocusPainted(false);
        SEIS.setFocusable(false);
        SEIS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SEIS.setPreferredSize(new java.awt.Dimension(50, 50));
        SEIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEISActionPerformed(evt);
            }
        });
        jPanel2.add(SEIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        CUATRO.setBackground(new java.awt.Color(51, 51, 51));
        CUATRO.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CUATRO.setForeground(new java.awt.Color(235, 236, 240));
        CUATRO.setText("4");
        CUATRO.setBorderPainted(false);
        CUATRO.setDefaultCapable(false);
        CUATRO.setFocusPainted(false);
        CUATRO.setFocusable(false);
        CUATRO.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CUATRO.setPreferredSize(new java.awt.Dimension(50, 50));
        CUATRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CUATROActionPerformed(evt);
            }
        });
        jPanel2.add(CUATRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        DOS.setBackground(new java.awt.Color(51, 51, 51));
        DOS.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        DOS.setForeground(new java.awt.Color(235, 236, 240));
        DOS.setText("2");
        DOS.setBorderPainted(false);
        DOS.setDefaultCapable(false);
        DOS.setFocusPainted(false);
        DOS.setFocusable(false);
        DOS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DOS.setPreferredSize(new java.awt.Dimension(50, 50));
        DOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOSActionPerformed(evt);
            }
        });
        jPanel2.add(DOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        UNO.setBackground(new java.awt.Color(51, 51, 51));
        UNO.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        UNO.setForeground(new java.awt.Color(235, 236, 240));
        UNO.setText("1");
        UNO.setBorderPainted(false);
        UNO.setDefaultCapable(false);
        UNO.setFocusPainted(false);
        UNO.setFocusable(false);
        UNO.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        UNO.setPreferredSize(new java.awt.Dimension(50, 50));
        UNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UNOActionPerformed(evt);
            }
        });
        UNO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UNOKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                UNOKeyReleased(evt);
            }
        });
        jPanel2.add(UNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        OCHO.setBackground(new java.awt.Color(51, 51, 51));
        OCHO.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        OCHO.setForeground(new java.awt.Color(235, 236, 240));
        OCHO.setText("8");
        OCHO.setBorderPainted(false);
        OCHO.setDefaultCapable(false);
        OCHO.setFocusPainted(false);
        OCHO.setFocusable(false);
        OCHO.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        OCHO.setPreferredSize(new java.awt.Dimension(50, 50));
        OCHO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OCHOActionPerformed(evt);
            }
        });
        jPanel2.add(OCHO, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        CINCO.setBackground(new java.awt.Color(51, 51, 51));
        CINCO.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CINCO.setForeground(new java.awt.Color(235, 236, 240));
        CINCO.setText("5");
        CINCO.setBorderPainted(false);
        CINCO.setDefaultCapable(false);
        CINCO.setFocusPainted(false);
        CINCO.setFocusable(false);
        CINCO.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CINCO.setPreferredSize(new java.awt.Dimension(50, 50));
        CINCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CINCOActionPerformed(evt);
            }
        });
        jPanel2.add(CINCO, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 280, 260));

        jPanel1.setBackground(new java.awt.Color(24, 27, 32));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PANTALLA.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N
        PANTALLA.setForeground(new java.awt.Color(204, 204, 204));
        PANTALLA.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(PANTALLA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 240, 30));

        INFIJA.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(INFIJA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 250, 30));

        RESULTADOP.setFont(new java.awt.Font("Microsoft Tai Le", 0, 36)); // NOI18N
        RESULTADOP.setForeground(new java.awt.Color(255, 255, 255));
        RESULTADOP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(RESULTADOP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 250, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RESTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESTActionPerformed
        S=S+"-";
        PANTALLA.setText(S);
    }//GEN-LAST:event_RESTActionPerformed

    private void UNOKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UNOKeyPressed

    }//GEN-LAST:event_UNOKeyPressed

    private void UNOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UNOKeyReleased

    }//GEN-LAST:event_UNOKeyReleased

    private void UNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UNOActionPerformed
        S=S+"1";
        PANTALLA.setText(S);
    }//GEN-LAST:event_UNOActionPerformed

    private void DOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOSActionPerformed
        S=S+"2";
        PANTALLA.setText(S);
    }//GEN-LAST:event_DOSActionPerformed

    private void TRESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TRESActionPerformed
        S=S+"3";
        PANTALLA.setText(S);
    }//GEN-LAST:event_TRESActionPerformed

    private void CUATROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CUATROActionPerformed
        S=S+"4";
        PANTALLA.setText(S);
    }//GEN-LAST:event_CUATROActionPerformed

    private void CINCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CINCOActionPerformed
        S=S+"5";
        PANTALLA.setText(S);
    }//GEN-LAST:event_CINCOActionPerformed

    private void SEISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEISActionPerformed
        S=S+"6";
        PANTALLA.setText(S);
    }//GEN-LAST:event_SEISActionPerformed

    private void SIETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIETEActionPerformed
        S=S+"7";
        PANTALLA.setText(S);
    }//GEN-LAST:event_SIETEActionPerformed

    private void OCHOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OCHOActionPerformed
        S=S+"8";
        PANTALLA.setText(S);
    }//GEN-LAST:event_OCHOActionPerformed

    private void NUEVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUEVEActionPerformed
        S=S+"9";
        PANTALLA.setText(S);
    }//GEN-LAST:event_NUEVEActionPerformed

    private void CEROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEROActionPerformed
        S=S+"0";
        PANTALLA.setText(S);
    }//GEN-LAST:event_CEROActionPerformed

    private void PAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PAActionPerformed
        S=S+"(";
        PANTALLA.setText(S);
    }//GEN-LAST:event_PAActionPerformed

    private void PBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PBActionPerformed
        S=S+")";
        PANTALLA.setText(S);
    }//GEN-LAST:event_PBActionPerformed

    private void SUMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUMAActionPerformed
        S=S+"+";
        PANTALLA.setText(S);
    }//GEN-LAST:event_SUMAActionPerformed

    private void MULTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MULTActionPerformed
        S=S+"*";
        PANTALLA.setText(S);
    }//GEN-LAST:event_MULTActionPerformed

    private void DIVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DIVActionPerformed
        S=S+"/";
        PANTALLA.setText(S);
    }//GEN-LAST:event_DIVActionPerformed

    private void CEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEActionPerformed
        S="";
        PANTALLA.setText(S);
        INFIJA.setText("");
        RESULTADOP.setText("");
        
    }//GEN-LAST:event_CEActionPerformed

    private void RESULTADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESULTADOActionPerformed
       if(comprobarp()&&comp()){                        
        arbolPrueba = new ArbolBinario<>();
        PostFija r=new PostFija();
        r.setEntrada(PANTALLA.getText());  
        r.convertir();
        Queue<String>cola=r.colaDeCadenas();
        arbolPrueba.expressionTree(cola);

        double calculado=arbolPrueba.calcular();
        
        if(calculado%1==0){
            int cal = (int) calculado;
            RESULTADOP.setText(""+cal);
            INFIJA.setText("POSFIJA: " +r.toString());
            S="";
        }else{
            RESULTADOP.setText(String.valueOf(calculado));
            INFIJA.setText("POSFIJA: " +r.toString());
            S="";
        }
        }else
       {
           JOptionPane.showMessageDialog(null,"ERROR:VERIFIQUE LOS PARENTESIS Y OPERADORES","ERROR",0,null);           
       }
    }//GEN-LAST:event_RESULTADOActionPerformed

    private void RESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESActionPerformed
       if(S.length()!=0){
        S=S.substring(0, S.length()-1);
        PANTALLA.setText(S);
       }
    }//GEN-LAST:event_RESActionPerformed

    private void POTENCIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_POTENCIAActionPerformed
        S=S+"^";
        PANTALLA.setText(S);
    }//GEN-LAST:event_POTENCIAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FProyecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CE;
    private javax.swing.JButton CERO;
    private javax.swing.JButton CINCO;
    private javax.swing.JButton CUATRO;
    private javax.swing.JButton DIV;
    private javax.swing.JButton DOS;
    private javax.swing.JLabel INFIJA;
    private javax.swing.JButton MULT;
    private javax.swing.JButton NUEVE;
    private javax.swing.JButton OCHO;
    private javax.swing.JButton PA;
    private javax.swing.JLabel PANTALLA;
    private javax.swing.JButton PB;
    private javax.swing.JButton POTENCIA;
    private javax.swing.JButton RES;
    private javax.swing.JButton REST;
    private javax.swing.JButton RESULTADO;
    private javax.swing.JLabel RESULTADOP;
    private javax.swing.JButton SEIS;
    private javax.swing.JButton SIETE;
    private javax.swing.JButton SUMA;
    private javax.swing.JButton TRES;
    private javax.swing.JButton UNO;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
